### ISSUE TITLE
Artboard where layer is selected to link is not exported

### ISSUE THREAD

**Issue by benjamin21st** [amin-nas/Sketch-to-Clickthrough-HTML#1]
Hello, thanks for creating this really cool plugin. I just installed it and it doesn't seem to work. When I link an artboard to a layer, and then select "Export to HTML", it exports every other artboards except the one where the link is. Do you know what is going on? 

The artboard can be exported once the links are removed, bizarre ...

**Comment by amin-nas** [comment]
Bizarre indeed!
Can you download the demo file and let me know if that works for you?
https://github.com/amin-nas/Sketch-to-Clickthrough-HTML/blob/master/demo/demo.sketch

If it does, I cant tell what's wrong without taking a peak at your file :)

**Comment by ChrisPlease** [comment]
+1

Demo works, my project doesn't export any artboard that has a link. 

Deleted demo links and retested, also works as expected. Only my projects don't generate the html file.

Version 41.2 (35397)

Edit: opened up a new demo project and it works there. Wonder if it has to do with how many elements are on the page? Sample sketch was really simple..

**Comment by amin-nas** [comment]
I've used the plugin with pages up to 40 artboards. Doubt that's the issue.
Just made a few tweaks and uploaded v1.2.1. 

If the issue remains, can you check your console for error messages?
