### ISSUE TITLE
Linking layers inside groups causes export to fail silently

### ISSUE THREAD

**Issue by zenoamaro** [amin-nas/Sketch-to-Clickthrough-HTML#3]
It is not possible to create a link from any layer that is inside a group – even though the README explicitly mentions that this is now possible.

The export will fail when it reaches the artboard containing the link, and remaining artboards won't be exported at all. The failure is silent – no output is displayed on the console. However, linking any top-level layer or group works as it should.

Attached is a test-case, created on Sketch 41.2 with version 1.2.1 of the plugin.

[Group testcase.zip](https://github.com/amin-nas/Sketch-to-Clickthrough-HTML/files/726765/Group.testcase.zip)

Note: This may actually be the root cause of #1.

**Comment by amin-nas** [comment]
Should be fixed in v1.2.2. 
Can you give it a try and confirm?

**Comment by zenoamaro** [comment]
Thanks, it works beautifully in v1.2.2, and I managed to get a perfect export.

However, I noticed that deeper groups, while they can be linked and exported, calculate their coordinates incorrectly. Fortunately, ungrouping that layer was easy.

Here is a testcase: [Deep groups testcase.zip](https://github.com/amin-nas/Sketch-to-Clickthrough-HTML/files/726951/Deep.groups.testcase.zip)

You can notice that the first button will work correctly, while the others are all placed on the top-left corner of the viewport.

**Comment by amin-nas** [comment]
v1.2.3 should address the nested links issue. Appreciate the QA! Let me know if you come across anything else.

**Comment by zenoamaro** [comment]
Looks perfect now! Thanks for the amazing work.
